"""Load processed MASContributionBench data.

`converters.py` creates unified JSONL files under `data/processed/tasks/`.
This module is the runtime-facing counterpart: experiment runners use it to
load TaskRecord objects, filter tasks, and build reproducible task subsets.
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from pydantic import ValidationError

from .schemas import DatasetName, TaskRecord


DATASET_TASK_FILES = {
    "humaneval": "humaneval_tasks.jsonl",
    "mbpp": "mbpp_tasks.jsonl",
    "teambench": "teambench_tasks.jsonl",
    "multiagentbench": "multiagentbench_tasks.jsonl",
    "marble": "marble_tasks.jsonl",
    "swebench_lite": "swebench_lite_tasks.jsonl",
    "aime_2026": "aime_2026_tasks.jsonl",
    "gpqa_diamond": "gpqa_diamond_tasks.jsonl",
    "hle": "hle_tasks.jsonl",
    "arc_agi_2": "arc_agi_2_tasks.jsonl",
    "ifbench": "ifbench_tasks.jsonl",
    "livecodebench": "livecodebench_tasks.jsonl",
    "swebench_verified": "swebench_verified_tasks.jsonl",
}


@dataclass(frozen=True)
class TaskLoadReport:
    path: Path
    total_lines: int
    loaded: int
    skipped_empty: int
    errors: list[str]

    @property
    def ok(self) -> bool:
        return not self.errors


class TaskLoadError(RuntimeError):
    """Raised when processed task data cannot be loaded safely."""


def _validate_task(payload: dict[str, Any]) -> TaskRecord:
    if hasattr(TaskRecord, "model_validate"):
        return TaskRecord.model_validate(payload)
    return TaskRecord.parse_obj(payload)


def _dataset_value(value: DatasetName | str) -> str:
    return value.value if isinstance(value, DatasetName) else str(value)


def iter_jsonl(path: str | Path) -> Iterable[tuple[int, dict[str, Any]]]:
    """Yield `(line_number, json_object)` from a JSONL file."""

    path = Path(path)
    with path.open("r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                raise
            yield line_number, payload


def load_jsonl_tasks(
    path: str | Path,
    *,
    strict: bool = True,
    return_report: bool = False,
) -> list[TaskRecord] | tuple[list[TaskRecord], TaskLoadReport]:
    """Load a processed task JSONL file as TaskRecord objects.

    Args:
        path: JSONL file generated by `prepare_data.py`.
        strict: If true, raise on the first malformed JSON or validation error.
            If false, collect bad rows in the report and keep loading.
        return_report: If true, return `(tasks, report)`.
    """

    path = Path(path)
    tasks: list[TaskRecord] = []
    errors: list[str] = []
    total_lines = 0
    skipped_empty = 0

    if not path.exists():
        raise FileNotFoundError(f"Task file does not exist: {path}")

    with path.open("r", encoding="utf-8") as f:
        for line_number, raw_line in enumerate(f, start=1):
            total_lines += 1
            line = raw_line.strip()
            if not line:
                skipped_empty += 1
                continue
            try:
                payload = json.loads(line)
                tasks.append(_validate_task(payload))
            except (json.JSONDecodeError, ValidationError, TypeError, ValueError) as exc:
                message = f"{path}:{line_number}: {type(exc).__name__}: {exc}"
                if strict:
                    raise TaskLoadError(message) from exc
                errors.append(message)

    report = TaskLoadReport(
        path=path,
        total_lines=total_lines,
        loaded=len(tasks),
        skipped_empty=skipped_empty,
        errors=errors,
    )
    if return_report:
        return tasks, report
    return tasks


def resolve_task_file(processed_root: str | Path, dataset: str) -> Path:
    """Return the expected processed JSONL path for a dataset."""

    dataset = dataset.lower()
    if dataset not in DATASET_TASK_FILES:
        known = ", ".join(sorted(DATASET_TASK_FILES))
        raise ValueError(f"Unknown dataset '{dataset}'. Known datasets: {known}")
    return Path(processed_root) / "tasks" / DATASET_TASK_FILES[dataset]


def load_dataset_tasks(
    processed_root: str | Path,
    dataset: str,
    *,
    split: str | None = None,
    task_ids: set[str] | list[str] | None = None,
    difficulty: str | set[str] | list[str] | None = None,
    max_tasks: int | None = None,
    seed: int | None = None,
    strict: bool = True,
) -> list[TaskRecord]:
    """Load one dataset and apply common experiment filters."""

    path = resolve_task_file(processed_root, dataset)
    tasks = load_jsonl_tasks(path, strict=strict)
    assert isinstance(tasks, list)
    return filter_tasks(
        tasks,
        dataset=dataset,
        split=split,
        task_ids=task_ids,
        difficulty=difficulty,
        max_tasks=max_tasks,
        seed=seed,
    )


def load_many_dataset_tasks(
    processed_root: str | Path,
    datasets: list[str],
    *,
    split: str | None = None,
    max_tasks_per_dataset: int | None = None,
    seed: int | None = None,
    strict: bool = True,
) -> list[TaskRecord]:
    """Load and concatenate tasks from multiple processed datasets."""

    all_tasks: list[TaskRecord] = []
    for dataset in datasets:
        all_tasks.extend(
            load_dataset_tasks(
                processed_root,
                dataset,
                split=split,
                max_tasks=max_tasks_per_dataset,
                seed=seed,
                strict=strict,
            )
        )
    ensure_unique_task_ids(all_tasks)
    return all_tasks


def filter_tasks(
    tasks: list[TaskRecord],
    *,
    dataset: str | None = None,
    split: str | None = None,
    task_ids: set[str] | list[str] | None = None,
    difficulty: str | set[str] | list[str] | None = None,
    max_tasks: int | None = None,
    seed: int | None = None,
) -> list[TaskRecord]:
    """Filter and optionally sample a task list."""

    selected = list(tasks)

    if dataset is not None:
        selected = [task for task in selected if _dataset_value(task.dataset) == dataset]

    if split is not None:
        selected = [task for task in selected if task.split == split]

    if task_ids is not None:
        wanted = set(task_ids)
        selected = [task for task in selected if task.task_id in wanted]

    if difficulty is not None:
        levels = {difficulty} if isinstance(difficulty, str) else set(difficulty)
        selected = [task for task in selected if task.difficulty.level in levels]

    if max_tasks is not None:
        if max_tasks < 0:
            raise ValueError("max_tasks must be non-negative")
        if seed is None:
            selected = selected[:max_tasks]
        else:
            rng = random.Random(seed)
            shuffled = list(selected)
            rng.shuffle(shuffled)
            selected = shuffled[:max_tasks]

    return selected


def ensure_unique_task_ids(tasks: list[TaskRecord]) -> None:
    """Raise if a task list contains duplicated task IDs."""

    seen: set[str] = set()
    duplicates: set[str] = set()
    for task in tasks:
        if task.task_id in seen:
            duplicates.add(task.task_id)
        seen.add(task.task_id)
    if duplicates:
        sample = ", ".join(sorted(duplicates)[:10])
        raise TaskLoadError(f"Duplicate task_id values found: {sample}")


def index_tasks_by_id(tasks: list[TaskRecord]) -> dict[str, TaskRecord]:
    """Return a task_id -> TaskRecord mapping after uniqueness validation."""

    ensure_unique_task_ids(tasks)
    return {task.task_id: task for task in tasks}


def summarize_tasks(tasks: list[TaskRecord]) -> dict[str, Any]:
    """Return a lightweight summary useful for validation logs."""

    by_dataset: dict[str, int] = {}
    by_split: dict[str, int] = {}
    by_type: dict[str, int] = {}
    by_difficulty: dict[str, int] = {}

    for task in tasks:
        dataset = _dataset_value(task.dataset)
        task_type = str(getattr(task.task_type, "value", task.task_type))
        by_dataset[dataset] = by_dataset.get(dataset, 0) + 1
        by_split[task.split] = by_split.get(task.split, 0) + 1
        by_type[task_type] = by_type.get(task_type, 0) + 1
        by_difficulty[task.difficulty.level] = by_difficulty.get(task.difficulty.level, 0) + 1

    return {
        "num_tasks": len(tasks),
        "by_dataset": dict(sorted(by_dataset.items())),
        "by_split": dict(sorted(by_split.items())),
        "by_task_type": dict(sorted(by_type.items())),
        "by_difficulty": dict(sorted(by_difficulty.items())),
    }
